configLeaderElection:
  leaseDuration: 60s
  renewDeadline: 40s
  retryPeriod: 10s
configLogging:
  loglevelController: info
  loglevelWebhook: info
  zapLoggerConfig: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
# Values for tekton-pipelines-controller
controller:
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: probes
    port: 8080
    targetPort: 0
  replicas: 1
  tektonPipelinesController:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
      tag: v0.37.2
    kubeconfigWriterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
      tag: v0.37.2
    gitImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
      tag: v0.37.2
    entrypointImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
      tag: v0.37.2
    nopImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop
      tag: v0.37.2
    imagedigestExporterImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter
      tag: v0.37.2
    prImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init
      tag: v0.37.2
    workingdirinitImage:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit
      tag: v0.37.2
    gsutilImage:
      repository: gcr.io/google.com/cloudsdktool/cloud-sdk
      tag:
      digest: sha256:27b2c22bf259d9bc1a291e99c63791ba0c27a04d2db0a43241ba0f1f20f4067f
    shellImage:
      repository: ghcr.io/distroless/busybox
      tag:
      digest: sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
    shellImageWin:
      repository: mcr.microsoft.com/powershell:nanoserver
      tag:
      digest: sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
  type: ClusterIP
# feature flags to put in feature-flags ConfigMap
featureFlags:
  # Setting this flag to "true" will prevent Tekton to create an
  # Affinity Assistant for every TaskRun sharing a PVC workspace
  #
  # The default behaviour is for Tekton to create Affinity Assistants
  #
  # See more in the workspace documentation about Affinity Assistant
  # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#affinity-assistant-and-specifying-workspace-order-in-a-pipeline
  # or https://github.com/tektoncd/pipeline/pull/2630 for more info.
  disableAffinityAssistant: "false"
  # Setting this flag to "true" will prevent Tekton scanning attached
  # service accounts and injecting any credentials it finds into your
  # Steps.
  #
  # The default behaviour currently is for Tekton to search service
  # accounts for secrets matching a specified format and automatically
  # mount those into your Steps.
  #
  # Note: setting this to "true" will prevent PipelineResources from
  # working.
  #
  # See https://github.com/tektoncd/pipeline/issues/2791 for more
  # info.
  disableCredsInit: "false"
  # Setting this flag will determine which gated features are enabled.
  # Acceptable values are "stable", "beta", or "alpha".
  enableApiFields: stable
  # Setting this flag to "true" enables the use of custom tasks from
  # within pipelines.
  # This is an experimental feature and thus should still be considered
  # an alpha feature.
  enableCustomTasks: "false"
  # Setting this flag to "true" enables the use of Tekton OCI bundle.
  # This is an experimental feature and thus should still be considered
  # an alpha feature.
  enableTektonOciBundles: "false"
  # Setting this flag to "true" will require that any Git SSH Secret
  # offered to Tekton must have known_hosts included.
  #
  # See https://github.com/tektoncd/pipeline/issues/2981 for more
  # info.
  requireGitSshSecretKnownHosts: "false"
  # This option should be set to false when Pipelines is running in a
  # cluster that does not use injected sidecars such as Istio. Setting
  # it to false should decrease the time it takes for a TaskRun to start
  # running. For clusters that use injected sidecars, setting this
  # option to false can lead to unexpected behavior.
  #
  # See https://github.com/tektoncd/pipeline/issues/2080 for more info.
  runningInEnvironmentWithInjectedSidecars: "true"
  # Setting this flag to "true" enables CloudEvents for Runs, as long as a
  # CloudEvents sink is configured in the config-defaults config map
  sendCloudeventsForRuns: "false"
kubernetesClusterDomain: cluster.local
# Values for tekton-pipelines-webhook
pipelinesInfo:
  version: v0.37.2
webhook:
  ports:
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: https-webhook
    port: 443
    targetPort: 8443
  - name: probes
    port: 8080
    targetPort: 0
  replicas: 1
  type: ClusterIP
  webhook:
    image:
      repository: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
      tag: v0.37.2
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
