kubernetesClusterDomain: cluster.local
shipwrightBuildController:
  replicas: 1
  shipwrightBuild:
    image:
      repository: ghcr.io/shipwright-io/build/shipwright-build-controller
      tag: v0.10.0
    GIT_CONTAINER_IMAGE:
      repository: ghcr.io/shipwright-io/build/git
      tag: v0.10.0
    MUTATE_IMAGE_CONTAINER_IMAGE:
      repository: ghcr.io/shipwright-io/build/mutate-image
      tag: v0.10.0
    BUNDLE_CONTAINER_IMAGE:
      repository: ghcr.io/shipwright-io/build/bundle
      tag: v0.10.0
    WAITER_CONTAINER_IMAGE:
      repository: ghcr.io/shipwright-io/build/waiter
      tag: v0.10.0
    BUILDER_CONTAINER_IMAGE_GO:
      repository: builder-go
      tag: bionic 
    BUILDER_CONTAINER_IMAGE_NODE:
      repository: builder-node
      tag: bionic 
    BUILDER_CONTAINER_IMAGE_PYTHON:
      repository: builder-python 
      tag: bionic 
    BUILDER_CONTAINER_IMAGE_JAVA:
      repository: builder-java
      tag: bionic 
